# Install as /etc/nginx/sites-available/birdcast-uk.conf and symlink into sites-enabled.

server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name uk-birdcast-workstation-ssh uk-birdcast 130.246.212.190 _;

    access_log /var/log/nginx/birdcast-uk-access.log;
    error_log /var/log/nginx/birdcast-uk-error.log;

    root /opt/birdcast-uk/site;
    index index.html;

    location /birdcast-uk/ {
        alias /opt/birdcast-uk/site/;
        try_files $uri $uri/ /index.html;
    }

    location = / {
        return 302 /birdcast-uk/;
    }
}
