"use strict";

const PALETTES={atlantic:["#061a2d","#0a4d68","#168aad","#52b69a","#d9ed92"],viridis:["#440154","#3b528b","#21918c","#5ec962","#fde725"],night:["#111827","#253b80","#497ed2","#9c85d8","#f3c4f1"],thermal:["#1d3557","#457b9d","#a8dadc","#f4a261","#e63946"]};
const state={base:"/europe-bird-maps/data",manifest:null,boundaries:null,day:null,date:null,frame:0,palette:"atlantic",vectors:true,playing:false,timer:null,view:{zoom:1,dx:0,dy:0},drag:null,grid:null};

init();
async function init(){
  const config=await fetchJson("config.json",{});state.base=config.data_base_url||state.base;
  state.manifest=await fetchJson(`${state.base}/latest/relative-flow.json`,null);state.boundaries=await fetchJson("regional-boundaries.geojson",null);
  if(!state.manifest||!state.manifest.data_available){unavailable();return}
  state.date=state.manifest.latest_time_utc.slice(0,10);configure();await loadDay();render();addEventListener("resize",draw);
}
async function fetchJson(url,fallback){try{const r=await fetch(url,{cache:"no-store"});if(!r.ok)throw Error(r.status);return await r.json()}catch(_){return fallback}}
function asset(path){return path&&path.startsWith("http")?path:`${state.base}/${String(path).replace(/^\//,"")}`}
function dayUrl(date){return asset(state.manifest.assets.daily_template.replace("{date}",date))}
async function loadDay(){state.day=await fetchJson(dayUrl(state.date),{frames:[]});state.frame=Math.min(state.frame,Math.max(0,state.day.frames.length-1))}
function configure(){
  const date=document.querySelector("#dateInput");date.min=state.manifest.first_time_utc.slice(0,10);date.max=state.manifest.latest_time_utc.slice(0,10);date.value=state.date;
  date.onchange=async()=>{stop();state.date=date.value;state.frame=0;await loadDay();render()};document.querySelector("#colourSelect").onchange=e=>{state.palette=e.target.value;render()};document.querySelector("#vectorsToggle").onchange=e=>{state.vectors=e.target.checked;draw()};
  document.querySelector("#hourInput").oninput=e=>{state.frame=+e.target.value;render()};document.querySelector("#play").onclick=()=>state.playing?stop():play();document.querySelector("#previous").onclick=()=>step(-1);document.querySelector("#next").onclick=()=>step(1);document.querySelector("#resetTime").onclick=async()=>{stop();state.date=state.manifest.first_time_utc.slice(0,10);state.frame=0;date.value=state.date;await loadDay();render()};
  document.querySelector("#zoomIn").onclick=()=>zoom(1.35);document.querySelector("#zoomOut").onclick=()=>zoom(1/1.35);document.querySelector("#resetMap").onclick=()=>{state.view={zoom:1,dx:0,dy:0};draw()};const canvas=document.querySelector("#mapCanvas");canvas.onwheel=e=>{e.preventDefault();zoom(e.deltaY<0?1.15:1/1.15)};canvas.onpointerdown=e=>{canvas.setPointerCapture(e.pointerId);state.drag={x:e.clientX,y:e.clientY,dx:state.view.dx,dy:state.view.dy}};canvas.onpointermove=e=>{if(state.drag){state.view.dx=state.drag.dx+e.clientX-state.drag.x;state.view.dy=state.drag.dy+e.clientY-state.drag.y;draw()}};canvas.onpointerup=canvas.onpointercancel=()=>{state.drag=null};
}
function current(){return state.day&&state.day.frames[state.frame]}
function render(){
  const f=current(),frames=state.day?state.day.frames:[],slider=document.querySelector("#hourInput");slider.max=Math.max(0,frames.length-1);slider.value=state.frame;document.querySelector("#hourOutput").textContent=f?new Date(f.time_utc).toISOString().slice(11,16):"--";
  document.querySelector("#timestamp").textContent=f?new Intl.DateTimeFormat("en-GB",{dateStyle:"medium",timeStyle:"short",timeZone:"UTC"}).format(new Date(f.time_utc))+" UTC":"No frame";const values=f?(f.radars||[]).map(r=>r.activity_index).filter(Number.isFinite):[];const mean=values.length?values.reduce((a,b)=>a+b,0)/values.length:null;document.querySelector("#networkValue").textContent=mean===null?"No reporting radars":`${mean.toFixed(0)} relative activity index`;
  document.querySelector("#statusBadge").textContent="Relative research product";document.querySelector("#subtitle").textContent=`${f?(f.radars||[]).length:0} reporting radars · activity normalised separately at every radar`;document.querySelector("#coverage").textContent=`${state.manifest.first_time_utc.slice(0,10)} to ${state.manifest.latest_time_utc.slice(0,10)} · ${state.manifest.radar_count} European reporting radars`;document.querySelector("#legendRamp").style.background=`linear-gradient(to top,${PALETTES[state.palette].join(",")})`;draw();
}
function draw(){
  const canvas=document.querySelector("#mapCanvas"),rect=canvas.getBoundingClientRect(),ratio=Math.min(3,devicePixelRatio||1);if(!rect.width||!rect.height)return;canvas.width=Math.round(rect.width*ratio);canvas.height=Math.round(rect.height*ratio);const c=canvas.getContext("2d");c.setTransform(ratio,0,0,ratio,0,0);c.fillStyle="#050807";c.fillRect(0,0,rect.width,rect.height);const p=projection(rect.width,rect.height);graticule(c,p,rect);relativeField(c,p);boundary(c,p);radars(c,p);
}
function projection(width,height){const bounds=state.manifest.map.bounds,pad=46,base=Math.min((width-pad*2)/(bounds.east-bounds.west),(height-pad*2)/(bounds.north-bounds.south)),scale=base*state.view.zoom,cx=(bounds.west+bounds.east)/2,cy=(bounds.south+bounds.north)/2;return(lon,lat)=>[width/2+(lon-cx)*scale+state.view.dx,height/2-(lat-cy)*scale+state.view.dy]}
function graticule(c,p,r){const b=state.manifest.map.bounds;c.strokeStyle="#344039";c.lineWidth=.65;c.beginPath();for(let lon=Math.floor(b.west/5)*5;lon<=b.east+5;lon+=5){const a=p(lon,b.south-3),z=p(lon,b.north+3);c.moveTo(...a);c.lineTo(...z)}for(let lat=Math.floor(b.south/5)*5;lat<=b.north+5;lat+=5){const a=p(b.west-3,lat),z=p(b.east+3,lat);c.moveTo(...a);c.lineTo(...z)}c.stroke()}
function rings(g){if(!g)return[];if(g.type==="Polygon")return g.coordinates;if(g.type==="MultiPolygon")return g.coordinates.flat();if(g.type==="LineString")return[g.coordinates];if(g.type==="MultiLineString")return g.coordinates;return[]}
function boundary(c,p){if(!state.boundaries)return;c.strokeStyle="#dce5df";c.lineWidth=1.05;for(const f of state.boundaries.features||[]){for(const ring of rings(f.geometry)){c.beginPath();ring.forEach(([x,y],i)=>i?c.lineTo(...p(x,y)):c.moveTo(...p(x,y)));c.stroke()}}}
function haversine(a,b,c,d){const rad=Math.PI/180,x=(c-a)*rad,y=(d-b)*rad,q=Math.sin(x/2)**2+Math.cos(a*rad)*Math.cos(c*rad)*Math.sin(y/2)**2;return 6371.0088*2*Math.atan2(Math.sqrt(q),Math.sqrt(1-q))}
function grid(){if(state.grid)return state.grid;const map=state.manifest.map,b=map.bounds,meta=state.manifest.radars||[],cells=[];for(let lat=Math.ceil(b.south/map.resolution_degrees)*map.resolution_degrees;lat<=b.north;lat+=map.resolution_degrees){for(let lon=Math.ceil(b.west/map.resolution_degrees)*map.resolution_degrees;lon<=b.east;lon+=map.resolution_degrees){const nearby=meta.map(r=>({radar:r.radar,distance:haversine(lat,lon,+r.latitude,+r.longitude)})).filter(r=>r.distance<=map.support_radius_km);if(nearby.length)cells.push({longitude:lon,latitude:lat,nearby})}}return state.grid=cells}
function relativeField(c,p){const f=current();if(!f)return;const observations=new Map((f.radars||[]).map(r=>[r.radar,r])),step=state.manifest.map.resolution_degrees;for(const cell of grid()){let weight=0,activity=0,u=0,v=0,flowWeight=0,nearest=Infinity;for(const near of cell.nearby){const r=observations.get(near.radar);if(!r||!Number.isFinite(r.activity_index))continue;const w=1/Math.max(25,near.distance)**2;weight+=w;activity+=w*r.activity_index;nearest=Math.min(nearest,near.distance);if(Number.isFinite(r.bird_u_ms)&&Number.isFinite(r.bird_v_ms)){const fw=w*(.2+r.activity_index/100);u+=fw*r.bird_u_ms;v+=fw*r.bird_v_ms;flowWeight+=fw}}if(!weight)continue;activity/=weight;const t=Math.max(0,Math.min(1,activity/100)),nw=p(cell.longitude-step/2,cell.latitude+step/2),se=p(cell.longitude+step/2,cell.latitude-step/2);c.globalAlpha=.22+.68*Math.max(0,1-nearest/state.manifest.map.support_radius_km);c.fillStyle=color(PALETTES[state.palette],t);c.fillRect(nw[0],nw[1],se[0]-nw[0]+1,se[1]-nw[1]+1);if(state.vectors&&flowWeight&&activity>=10&&Math.round((cell.longitude*4)+(cell.latitude*4))%4===0)arrow(c,(nw[0]+se[0])/2,(nw[1]+se[1])/2,u/flowWeight,v/flowWeight)}c.globalAlpha=1}
function radars(c,p){for(const radar of state.manifest.radars||[]){const[x,y]=p(+radar.longitude,+radar.latitude);c.fillStyle="#d7f4ea";c.strokeStyle="#0b1512";c.lineWidth=2;c.beginPath();c.arc(x,y,3.4,0,Math.PI*2);c.fill();c.stroke()}}
function arrow(c,x,y,u,v){const speed=Math.hypot(u,v);if(speed<.2)return;const len=13,angle=Math.atan2(-v,u),ex=x+Math.cos(angle)*len,ey=y+Math.sin(angle)*len;c.strokeStyle="#020303";c.fillStyle="#020303";c.lineWidth=1.6;c.beginPath();c.moveTo(x,y);c.lineTo(ex,ey);c.stroke();c.beginPath();c.moveTo(ex,ey);c.lineTo(ex-5*Math.cos(angle-.55),ey-5*Math.sin(angle-.55));c.lineTo(ex-5*Math.cos(angle+.55),ey-5*Math.sin(angle+.55));c.closePath();c.fill()}
function color(p,t){const x=Math.max(0,Math.min(1,t))*(p.length-1),i=Math.min(p.length-2,Math.floor(x)),f=x-i,a=rgb(p[i]),b=rgb(p[i+1]);return`rgb(${a.map((v,j)=>Math.round(v+(b[j]-v)*f)).join(",")})`}function rgb(h){return[parseInt(h.slice(1,3),16),parseInt(h.slice(3,5),16),parseInt(h.slice(5,7),16)]}
function zoom(f){state.view.zoom=Math.max(.65,Math.min(8,state.view.zoom*f));draw()}async function step(delta){stop();await move(delta);render()}async function move(delta){let n=state.frame+delta;if(n>=0&&n<(state.day.frames||[]).length){state.frame=n;return}const d=new Date(`${state.date}T00:00:00Z`);d.setUTCDate(d.getUTCDate()+(delta>0?1:-1));const next=d.toISOString().slice(0,10),min=state.manifest.first_time_utc.slice(0,10),max=state.manifest.latest_time_utc.slice(0,10);if(next<min||next>max)return;state.date=next;document.querySelector("#dateInput").value=next;await loadDay();state.frame=delta>0?0:Math.max(0,state.day.frames.length-1)}function play(){state.playing=true;document.querySelector("#play").textContent="Pause";state.timer=setInterval(async()=>{await move(1);render()},650)}function stop(){state.playing=false;clearInterval(state.timer);state.timer=null;document.querySelector("#play").textContent="Play"}function unavailable(){document.querySelector("#statusBadge").textContent="Unavailable";document.querySelector("#subtitle").textContent="Relative European analysis has not been published";document.querySelectorAll("input,select,button").forEach(e=>e.disabled=true)}
